### ISSUE TITLE
Determine evolutionary conservation of TMHs

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/bbbq_article#26]
Depends on:

 * [x] Get msa installed on Peregrine, #60 
 * [ ] Getting it to run on Travis, #61 
 * [x] Getting it to run on Peregrine, #63
 * [x] Add a plot function, #64 

Something like this:

![fig_evolutionary_conservation_of_tmhs](https://user-images.githubusercontent.com/2098230/88523043-957b9f00-cff7-11ea-819e-4612b667f24f.png)
